version: '3'
services:
  checkout-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/src
    ports:
      - "8080:8080"
  checkout-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"