# Node LTS image apline
FROM node:18-alpine

# Set Node ENV
ENV NODE_ENV=development
RUN echo $NODE_ENV

# Install nodemon for hotreloading
RUN yarn global add nodemon

# Set working directory
WORKDIR /src

CMD ["nodemon", "server.js"]
EXPOSE 8080